config/routes.rb
Rails.application.routes.draw do

  root to: 'listen#index'

  get '/profile', to: 'admin/users#profile'

  get 'login', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  resources :sessions, only: [:create]
  
  resources :listen, only: [:index, :show]

  resources :broadcast, only: [:index, :show]

  namespace :admin do
    
    resources :channels, except: [:show]

    resources :users, except: [:show]
    
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base

  validates :name, presence: true, length: { maximum: 80 }
  validates :description, presence: true
  validates :image, presence: true

  before_save :generate_slug, :generate_token

  mount_uploader :image, BannerUploader

  private

  def generate_slug
    self.slug = self.name.parameterize
  end

  def generate_token
     self.token = SecureRandom.hex(20)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password({ validations: false })

  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 15 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 5 }, confirmation: true, :unless => lambda { |v| v.validate_password? }
  validates :level, presence: true

  def validate_password?
    password.blank? && password_confirmation.blank? && !self.new_record?
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/channels_controller.rb
class Admin::ChannelsController < Admin::BaseController
  before_action { |c| c.authorize_level(2) }

  def index
    @table = Table.new(self, Channel, nil, search: true)
    @table.respond
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to admin_channels_path, success: "Channel créée"
    else
      render 'new'
    end
  end

  def edit
    @channel = Channel.find(params[:id])
  end

  def update
    @channel = Channel.find(params[:id])
    if @channel.update_attributes(channel_params)
      redirect_to admin_channels_path, success: "Channel enregistrée"
    else
      render 'edit'
    end
  end

  def destroy
    Channel.find(params[:id]).destroy
    redirect_to admin_channels_path, success: "Channel supprimé"
  end

  private

  def channel_params
    params.require(:channel).permit(:description, :name, :private, :image)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action { |c| c.authorize_level(1) }

  def index
    @table = Table.new(self, User)
    @table.respond
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, success: "Utilisateur crée"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_users_path, success: "Utilisateur enregistré"
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_activities_path, success: "Utilisateur supprimé"
  end

  def profile
  end

  private

  def user_params
    params.require(:user).permit(:name, :level, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :error, :success, :notice

  include ApplicationHelper
  include SessionsHelper

  helper_method :authorize_level?

  def js(enabled, **args)
    @js = enabled
    @js_params = args
  end

  # Store the current url in session's variable
  # 
  # * *Args*    :
  # 
  # * *Returns* :
  #
  def store_location
    cookies[:return_to] = { value: request.fullpath, expires: 1.minute.from_now }
  end

  # Redirect the user to the stored url or the default one provided
  # 
  # * *Args*    :
  #   - default path to redirect to
  # * *Returns* :
  #
  def redirect_back_or(default, message = nil)
    redirect_to(cookies[:return_to] || default, message)
    session.delete(:return_to)
  end

  def authorize_level?(level = 4)
    current_user && current_user.level <= level
  end

  def authorize_level(level = 4)
    unless authorize_level?(level)
      store_location
      redirect_to login_path, error: "Pas autorisé"
    end
  end

end

app/controllers/broadcast_controller.rb
class BroadcastController < ApplicationController
  before_action { |c| c.authorize_level(3) }

  def index
    @channels = Channel.all
  end

  def show
    @channel = Channel.find_by_slug!(params[:id])
    js true, token: @channel.token
    render 'show', turbolinks: false
  end
end

app/controllers/listen_controller.rb
class ListenController < ApplicationController
  before_action :disallow_private, only: [:show]

  def index
    @channels = Channel.where(private: false)
  end

  def show
    js true, token: @channel.token
  end

  private

  def disallow_private
    @channel = Channel.find_by_slug!(params[:id])
    if @channel.private
      redirect_to listen_path, error: "Cette channel est privée"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :connected?, except: :destroy

  def new
  end

  def create
    @user = User.where("lower(name) = ?", params[:session][:name].strip.downcase).first
    if @user && @user.authenticate(params[:session][:password])
      params[:session][:remember_me] == '1' ? sign_in_permanent(@user) : sign_in(@user)
      redirect_back_or profile_path, success: "Connecté !"
    else
      flash.now[:error] = "Nom d'utilisateur et/ou mot de passe erroné"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path, success: "Déconnecté !"
  end

  private

  def connected?
    redirect_to profile_path unless current_user.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def ng_controller
    {"ng-controller" => "#{params[:controller]}##{params[:action]}"} if @js
  end

  def js_params
    @js_params || {}
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Sign in a user with a cookie (remove on browser close)
	# 
	# * *Args*		:
	# 	- a user to sign in
	# * *Returns*	:
	#
	def sign_in(user)
		cookies[:remember_token] = user.remember_token
		self.current_user = user
	end

	# Sign in a user with a cookie (remove after 2 months)
	# 
	# * *Args*		:
	# 	- a user to sign in
	# * *Returns*	:
	#
	def sign_in_permanent(user)
		cookies[:remember_token] = { value: user.remember_token, expires: Time.now + 2592000 }
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	# Provid the user currently signed in.
	# 
	# * *Returns*	:
	# 	- the user currently signed in
	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end


	# Check if there is a user signed in.
	# 
	# * *Returns*	:
	# 	- true or false
	def signed_in?
		!current_user.nil?
	end

	# Sign out a user by removing the cookie.
	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

end

app/views/admin/channels/_form.html.erb
<%= form_for [:admin, @channel] do |f| %>

  <%= render 'error_messages', object: f.object %>

  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </li>
    <li>
      <%= f.label :private %>
      <%= f.check_box :private %>
    </li>
    <li>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </li>
  </ul>
  
  <ul>
    <li>
      <%= f.submit %>
    </li>
  </ul>

<% end %>

app/views/admin/channels/edit.html.erb
<h1>Mettre à jour une channel</h1>

<%= render 'form' %>

app/views/admin/channels/index.html.erb
<h1>Les channels</h1>

<%= @table.present %>

app/views/admin/channels/new.html.erb
<h1>Créer une nouvelle channel</h1>

<%= render 'form' %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>

	<%= render 'error_messages', object: f.object %>
	<ul>
		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</li>
		<li>
			<%= f.label :password %>
			<%= f.password_field :password %>
		</li>
	</ul>
	<ul>
		<li>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
		</li>
		<li>
			<%= f.label :level %>
			<%= f.select :level, {"superadmin" => "1", "admin" => "2", "broadcaster" => "3", "listener" => "4"} %>
		</li>
	</ul>

	<ul>
		<li>
			<%= f.submit %>
		</li>
	</ul>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editer un utilisateur</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Utilisateurs</h1>

<div id="admin_table">
	<%= @table.present %>
</div>

app/views/admin/users/new.html.erb
<h1>Ajouter un utilisateur</h1>

<%= render 'form' %>

app/views/admin/users/profile.html.erb
<p>
	<%= link_to "Broadcast", "/broadcast" if authorize_level?(3) %> • 
	<%= link_to "Channels", admin_channels_path if authorize_level?(2) %> • 
	<%= link_to "Utilisateurs", admin_users_path if authorize_level?(1) %>
</p>

app/views/application/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="clear"></div>
  <div id="error">
    <p class="title">
      <%= t 'activemodel.errors.messages', count: object.errors.count %>
    </p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <div id="clear"></div>
<% end %>

app/views/application/_js_params.js.erb
app.service('params', function(){
  return <%= js_params.to_json.html_safe %>;
});

app/views/broadcast/index.html.erb
<% content_for :id, "broadcast" %>

<h1>Diffuser sur une channel</h1>
<p class="subtitle">Choisissez laquelle vous souhaitez utiliser<p>

<ul>
	<% @channels.each do |channel| %>
	<li>
	  <h3><%= channel.name %></h3>
	  <p>
	  	• <%= link_to image_tag("broadcast/media19.png"), broadcast_path(channel.slug) %>
	  	<%= channel.description %>
	  	<%= link_to "Broadcaster", broadcast_path(channel.slug), "data-no-turbolink" => true %>
		</p>
	</li>
	<% end %>
</ul>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, id: "flash", class: "flash-#{key}" do %>
        <%= value %>
        <span class="close">fermer</span>
      <% end %>
    <% end %>
<% end %>

<div class="ng-hide" id="message">
  <div>{{ message }}</div>
 <span class="close">fermer</span>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <% if current_user.nil? %>
    <p><%= link_to "Login", login_path %></p>
  <% else %>
    <p>
      <%= link_to current_user.name, profile_path %> | 
      <%= link_to "Déconnecter", signout_path %>
    </p>
  <% end %>
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greedo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <script>
    <%= render "js_params.js.erb" %>
  </script>

  <%= content_tag :div, ng_controller do %>

  <%= render 'layouts/flash' %>
  <%= link_to image_tag("layout/greedo.png", id: 'logo'), root_path %>
  <%= render 'layouts/admin_header' %>

  <div id="container">
    <%= yield %>
  </div>

  <% end %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greedo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <script>
    <%= render "js_params.js.erb" %>
  </script>

  <%= content_tag :div, ng_controller do %>

  <%= render 'layouts/flash' %>
  <%= link_to image_tag("layout/greedo.png", id: 'logo'), root_path %>
  <%= render 'layouts/header' %>

  <div id="container" class="<%= (yield :id) %>">
    <%= yield %>
  </div>

  <% end %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/listen/index.html.erb
<% content_for :id, "listen" %>

<h1>Tous les channels disponibles</h1>
<p class="subtitle">Choisissez le channel que vous souhaitez écouter<p>

<ul>
<% @channels.each do |channel| %>
  <li>
	  <h3><%= link_to channel.name, listen_path(channel.slug) %></h3>
	  <p>
	  	• <%= link_to image_tag("listen/sound48.png"), listen_path(channel.slug) %>
	  	<%= channel.description %> <%= link_to "Ecouter", listen_path(channel.slug) %>
	  </p>
	</li>
<% end %>
</ul>

app/views/listen/show.html.erb
<% content_for :id, "listen-show" %>

<h1><%= @channel.name %></h1>

<p>{{ warning }}</p>

<p><%= link_to "↩ Retour à la liste", "/listen" %></p>

<audio controls autoplay></audio>